debug: false
uuid: <UUID>
token-id: <TOKEN_ID>
token: <TOKEN>

api:
    host: 0.0.0.0
    port: 8080
    ssl:
        enabled: false
        certificate: /etc/elytra/certificate.pem
        key: /etc/elytra/certificate.key
    upload-limit: 100
    trusted-proxies: <TRUSTED_PROXIES>

system:
    data: /var/lib/elytra/volumes
    archive: /var/lib/elytra/archives
    backup: /var/lib/elytra/backups
    tmpfs_size: 100
    websocket_log_count: 150
    check_permissions_on_boot: false

allowed-mounts: []
allowed-origins: []

remote: <REMOTE>
remote_query:
    timeout: 10
    interval: 60
    always: false

docker:
    network:
        interface: 172.18.0.1
        gateway: 172.18.0.1
        subnet: 172.18.0.0/16
        mtu: 1500
    domainname: ""
    registries: {}
    tmpfs:
        size: 100
        mode: 1777
    container_pid_limit: 2048
    installer_limits:
        memory: 2048
        cpu: 200

throttles:
    enabled: true
    lines: 1000
    line_reset_interval: 100
    maximum_trigger_count: 5
    decay_interval: 10000
    stop_grace_period: 15
    write_limit: 0
    download_limit: 0

installed: true
